# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 03:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20, unique=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('review_type', models.CharField(blank=True, choices=[('exempt review', 'Exempt Review'), ('expedited review', 'Expedited Review'), ('full irb review', 'Full IRB Review')], max_length=20)),
                ('consent_form', models.FileField(blank=True, upload_to='')),
                ('assent_form', models.FileField(blank=True, upload_to='')),
                ('surveys_form', models.FileField(blank=True, upload_to='')),
                ('methodology_form', models.FileField(blank=True, upload_to='')),
                ('grant_proposal_form', models.FileField(blank=True, upload_to='')),
                ('ext_circumstances_form', models.FileField(blank=True, upload_to='')),
                ('principal_investigator_signature', models.FileField(blank=True, upload_to='')),
                ('faculty_supervisor_signature', models.FileField(blank=True, upload_to='')),
                ('funding', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('methodology', models.CharField(blank=True, max_length=500)),
                ('benefits', models.CharField(blank=True, max_length=500)),
                ('risk', models.CharField(blank=True, max_length=500)),
                ('recruited', models.CharField(blank=True, max_length=500)),
                ('why_identify', models.CharField(blank=True, max_length=500)),
                ('how_data_store', models.CharField(blank=True, max_length=500)),
                ('consent_process', models.CharField(blank=True, max_length=500)),
                ('review_notes', models.CharField(blank=True, max_length=500)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
