# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='consent_form',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
