# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('review_type', models.CharField(max_length=10)),
                ('consent_form', models.FileField(upload_to='')),
                ('assent_form', models.FileField(upload_to='')),
                ('surveys_form', models.FileField(upload_to='')),
                ('methodology_form', models.FileField(upload_to='')),
                ('grant_proposal_form', models.FileField(upload_to='')),
                ('ext_circumstances_form', models.FileField(upload_to='')),
                ('principal_investigator_signature', models.FileField(upload_to='')),
                ('faculty_supervisor_signature', models.FileField(upload_to='')),
                ('funding', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.CharField(max_length=500)),
                ('methodology', models.CharField(max_length=500)),
                ('benefits', models.CharField(max_length=500)),
                ('risk', models.CharField(max_length=500)),
                ('recruited', models.CharField(max_length=500)),
                ('why_identify', models.CharField(max_length=500)),
                ('how_data_store', models.CharField(max_length=500)),
                ('consent_process', models.CharField(max_length=500)),
                ('review_notes', models.CharField(max_length=500)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irbSite.User')),
            ],
        ),
    ]
