# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_submitted',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='assent_form',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='benefits',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='consent_form',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='consent_process',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ext_circumstances_form',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='faculty_supervisor_signature',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='grant_proposal_form',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='how_data_store',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='methodology',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='methodology_form',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='principal_investigator_signature',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='purpose',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='recruited',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='review_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='review_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='surveys_form',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='why_identify',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
