# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0003_auto_20180405_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='review_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
