# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0003_auto_20180420_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
