# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0005_auto_20180405_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='last_modified',
        ),
    ]
