# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0006_auto_20180405_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
