# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0009_auto_20180405_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='review_type',
            field=models.CharField(blank=True, choices=[('exempt review', 'Exempt Review'), ('expedited review', 'Expedited Review'), ('full irb review', 'Full IRB Review')], max_length=10),
        ),
    ]
