# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0010_auto_20180421_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='benefits',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='consent_process',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='how_data_store',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='methodology',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='purpose',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='recruited',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='review_notes',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='why_identify',
            field=models.CharField(max_length=3000),
        ),
    ]
