# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0010_auto_20180406_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='irbSite.User'),
        ),
    ]
