# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0014_auto_20180406_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=20),
        ),
    ]
