# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0018_auto_20180406_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='review_type',
            field=models.CharField(choices=[('exempt review', 'Exempt Review'), ('expedited review', 'Expedited Review'), ('full irb review', 'Full IRB Review')], max_length=10),
        ),
    ]
