# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 18:43
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0021_auto_20180406_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combined',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='irbSite.Project')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('irbSite.user', 'irbSite.project'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
