# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irbSite', '0021_auto_20180406_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assent_form',
            field=models.FileField(blank=True, null=True, upload_to='forms/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='consent_form',
            field=models.FileField(blank=True, null=True, upload_to='forms/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ext_circumstances_form',
            field=models.FileField(blank=True, null=True, upload_to='forms/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='faculty_supervisor_signature',
            field=models.FileField(blank=True, null=True, upload_to='forms/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='grant_proposal_form',
            field=models.FileField(blank=True, null=True, upload_to='forms/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='methodology_form',
            field=models.FileField(blank=True, null=True, upload_to='forms/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='principal_investigator_signature',
            field=models.FileField(blank=True, null=True, upload_to='forms/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='surveys_form',
            field=models.FileField(blank=True, null=True, upload_to='forms/%Y/%m/%D/'),
        ),
    ]
