# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('irbSite', '0022_combined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combined',
            name='project_ptr',
        ),
        migrations.DeleteModel(
            name='Combined',
        ),
    ]
